### ISSUE TITLE
Command error for "/lootbags_itemdump"

### ISSUE THREAD

**Issue by Briaker** [Malorolam/LootBags#18]
The command "/lootbags_itemdump" causes the server to return an error. This error occurs in 2.0.4 and in 2.0.8. I've tried to manually create the "dumps" folder with the "LootBagsItemDump.txt"  file inside of it (in the servers' root and in the clients' root), but there was no change.

Error message from in-game chat: 
> An unknown error occurred while attempting to perform this command

Error message from server console: 
`[16:33:08] [Server thread/ERROR]: Couldn't process command: 'lootbags_itemdump'
java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at mal.lootbags.handler.ItemDumpCommand.func_71515_b(ItemDumpCommand.java:98) ~[ItemDumpCommand.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]`

**Comment by Malorolam** [comment]
Should be fixed in 2.0.9.

**Comment by Briaker** [comment]
Thanks for the quick fix!
