### ISSUE TITLE
Server crash because of faulty lootbag in lootbag opener

### ISSUE THREAD

**Issue by Autom3** [Malorolam/LootBags#62]
Mod version: lootbags{2.3.2} [Loot Bags] (LootBags-1.10.2-2.3.2.jar)

Here's the stacktrace:
```
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at mal.lootbags.item.LootbagItem.getNumItems(LootbagItem.java:407)
        at mal.lootbags.item.LootbagItem.generateInventory(LootbagItem.java:174)
        at mal.lootbags.tileentity.TileEntityOpener.func_73660_a(TileEntityOpene
r.java:64)
        at net.minecraft.world.World.func_72939_s(World.java:1804)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:709)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Thread.java:745)
```

Hopefully this is of use

**Comment by Malorolam** [comment]
That crash can only happen if the bag associated with that ID doesn't exist, which either happens if you remove or change bag IDs in the bag config in an active world, or a different mod is messing with item metadata.  There will be better handling for this in the next version.

**Comment by Autom3** [comment]
One of my players got it, but they don't know how. We were running the foolcraft 1.2.2 modpack with default configs.

Thanks for the quick reply!
