### ISSUE TITLE
Bags crashing, custom config

### ISSUE THREAD

**Issue by red3dred** [Malorolam/LootBags#8]
So, i've been tinkering with this mod for a while, and while i was playing single-player normally, everything was working well and crash-less-ly... However, opening bags with a custom config somehow makes them crash.
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 31/10/15 03:40
Description: Ticking memory connection

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at net.minecraftforge.common.ChestGenHooks.generateStacks(ChestGenHooks.java:111)
	at mal.lootbags.LootMap.getRandomItem(LootMap.java:404)
	at mal.lootbags.item.LootbagItem.getLootItem(LootbagItem.java:397)
	at mal.lootbags.item.LootbagItem.getLootItem(LootbagItem.java:326)
	at mal.lootbags.item.LootbagItem.generateInventory(LootbagItem.java:304)
	at mal.lootbags.item.LootbagItem.func_77659_a(LootbagItem.java:524)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.Random.nextInt(Unknown Source)
	at net.minecraftforge.common.ChestGenHooks.generateStacks(ChestGenHooks.java:111)
	at mal.lootbags.LootMap.getRandomItem(LootMap.java:404)
	at mal.lootbags.item.LootbagItem.getLootItem(LootbagItem.java:397)
	at mal.lootbags.item.LootbagItem.getLootItem(LootbagItem.java:326)
	at mal.lootbags.item.LootbagItem.generateInventory(LootbagItem.java:304)
	at mal.lootbags.item.LootbagItem.func_77659_a(LootbagItem.java:524)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@4b146ff1
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 142100456 bytes (135 MB) / 619184128 bytes (590 MB) up to 1521483776 bytes (1451 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1536M -Xmn256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	PlayerAPI{1.2} [Player API] (minecraft.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
	UCHIJAAAA	MovingWorld{1.7.10-1.8} [Moving World] (movingworld-1.7.10-1.8.jar) 
	UCHIJAAAA	ArchimedesShipsPlus{1.7.10-1.8} [Archimedes' Ships Plus] (archimedesshipsplus-1.7.10-1.8.jar) 
	UCHIJAAAA	armourersWorkshop{1.7.10-0.31.2.82} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.31.2.82.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJAAAA	bettervillages{0.4} [Better Villages Mod] (BetterVillages-0.4(1.7.10).jar) 
	UCHIJAAAA	BuildCraft|Core{6.3.7} [BuildCraft] (buildcraft-6.3.7.jar) 
	UCHIJAAAA	BuildCraft|Transport{6.3.7} [BC Transport] (buildcraft-6.3.7.jar) 
	UCHIJAAAA	BuildCraft|Silicon{6.3.7} [BC Silicon] (buildcraft-6.3.7.jar) 
	UCHIJAAAA	BuildCraft|Builders{6.3.7} [BC Builders] (buildcraft-6.3.7.jar) 
	UCHIJAAAA	BuildCraft|Energy{6.3.7} [BC Energy] (buildcraft-6.3.7.jar) 
	UCHIJAAAA	BuildCraft|Factory{6.3.7} [BC Factory] (buildcraft-6.3.7.jar) 
	UCHIJAAAA	craftguide{1.6.8.2} [CraftGuide] (CraftGuide-1.6.8.2-forge.jar) 
	UCHIJAAAA	exnihilo{1.38-48} [Ex Nihilo] (Ex-Nihilo-1.38-48.jar) 
	UCHIJAAAA	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	Metallurgy{4.0.8} [Metallurgy 4] (Metallurgy-1.7.10-4.0.8.97.jar) 
	UCHIJAAAA	exastrisrebirth{MC1.7.10-1.01-45} [Ex Astris Rebirth] (Ex-Astris-Rebirth-MC1.7.10-1.01-45.jar) 
	UCHIJAAAA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJAAAA	rftl{1.7.10} [Rotten Flesh to Leather] (Forge SSP SMP - Rotten Flesh 1.7.2 1.7.10.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) 
	UCHIJAAAA	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCHIJAAAA	levelup{0.10} [Level Up!] (LevelUp!-0.10(1.7.10).jar) 
	UCHIJAAAA	lootbags{1.8.1} [Loot Bags] (LootBags-1.7.10-1.8.1.jar) 
	UCHIJAAAA	RadixCore{2.1.0} [RadixCore] (RadixCore-1.7.10-2.1.0-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.1.0} [Minecraft Comes Alive] (MCA-1.7.10-5.1.0-universal.jar) 
	UCHIJAAAA	mochickens{1.6.1} [Mo Chickens] (MoChickens-1.7.10-1.6.1.jar) 
	UCHIJAAAA	Ping{%MOD_VERSION} [Ping] (Ping-1.7.X-1.0.2.B6-universal.jar) 
	UCHIJAAAA	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) 
	UCHIJAAAA	quiverchevsky{b100} [QuiverBow] (QuiverBow_1.7.10_b100.zip) 
	UCHIJAAAA	Roguelike{1.3.5} [Roguelike Dungeons] (roguelike-1.7.10-1.3.5.jar) 
	UCHIJAAAA	AS_Ruins{14.6} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.377.jar) 
	UCHIJAAAA	SpecialMobs{3.0.3} [Special Mobs] (SpecialMobs-1.7.10-3.0.3.jar) 
	UCHIJAAAA	SwordPedestal{1.1(1.7.10)} [Sword Pedestal] (SwordPedestal-1.1(1.7.10).jar) 
	UCHIJAAAA	TKE{2.3} [The Kappa Experience] (TheKappaExperience-1.7.10-2.3.jar) 
	UCHIJAAAA	TooMuchTNT{2.9} [TooMuchTNT] (TooMuchTNT v2.9.jar.zip) 
	UCHIJAAAA	TragicMC{2.44.2776 Beta} [TragicMC 2] (TragicMC2-1.7.10-2.44.2776B.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['red3dred'/71, l='New World', x=249,01, y=4,00, z=-1090,57]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by red3dred** [comment]
I attempted clearing all ChestGenHooks from the config and that didn't solve anything. Just pointing that out, in case it may help.

**Comment by Malorolam** [comment]
Can you post the config as well?  I recall there being a similar crash, but I don't remember what caused it.  I know an error in the config causes that crash, and I think there was a mod that had malformed loot table entries, but both cases cause crashes in singleplayer as well.  I can't offer much more help right now than find what the item(s) are and take them out of the config for now, I'm in the middle of rewriting the mod (slowly).
